import os
pj = os.path.join

Import('baseEnv PREFIX GetPlatform')

headers = Split("""
GlutDriver.h
""")

sources = Split("""
GlutDriver.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #gk #cppdom #external/xdl'),
           LIBPATH = Split('#cppdom/cppdom #gk /usr/local/lib'),
           LIBS = Split('gk cppdom glut') )
env.Append(CXXFLAGS = ['-DXDL_BUILD_DLL'])

if GetPlatform() == 'irix':
   env['SHCXXFLAGS'] = '${CXXFLAGS}'

env.Replace(SHLIBPREFIX = '',
            SHLIBSUFFIX = '')

lib = env.SharedLibrary('glut.gkd', sources)
env.Install(pj(PREFIX, 'lib'), lib)
for h in headers:
	env.Install(pj(PREFIX, 'include'), h)
