import os
pj = os.path.join

Import('pkg baseEnv PREFIX GetPlatform')

headers = Split("""
GlutDriver.h
""")

sources = Split("""
GlutDriver.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #gk #cppdom #external/xdl'),
           LIBPATH = Split('#cppdom/cppdom #gk /usr/local/lib'),
           LIBS = Split('gk cppdom glut') )
env.Append(CXXFLAGS = ['-DXDL_BUILD_DLL', '-DWIN32'])

if GetPlatform() == 'irix':
   env['SHCXXFLAGS'] = '${CXXFLAGS}'

#lib = pkg.createStaticLibrary('glut.gk', env)

lib = pkg.createSharedLibrary('glut.gk', env)
lib.addSources(sources)
lib.addHeaders(headers, 'glut.gk')


