Import('env')

classes = [
   'MessageQueue',
]

headers = [
   'ByteBuffer',
   'InputStream',
   'LoginMessage',
   'Message',
   'MessageReader',
   'MessageTypes',
   'OKMessage',
   'OutputStream',
   'Serialize',
   'ServerSocket',
   'SocketException',
   'Socket',
   'StreamException',
]

sources = [
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

# add in the files from classes
headers.extend( map(lambda fn: fn + '.h', classes) )
sources.extend( map(lambda fn: fn + '.cpp', classes) )

env.Library(target = 'net', source = sources)
