import glob
import os
pj = os.path.join

Import('baseEnv builddir')

env = baseEnv.Copy()

# Resources listing
env.Install('../../dist', str(File('#data/resources.txt')))

# Key bindings
env.Install('../../dist/data', str(File('#data/inputbindings.txt')))


# Avatars
avatar_files = glob.glob(pj(str(Dir('#data/avatars')), '*.*'))
for file in avatar_files:
   env.Install('../../dist/data/avatars', file)
