# build with 'scons'

Default('.')        # build everything by default
# setup the environment
env = Environment(CPPPATH=Dir('.'))
Export('env')
SConscript('phui/SConscript')
SConscript('examples/SConscript')
