import os
pj = os.path.join

Import('pkg baseEnv PREFIX GetPlatform')

headers = Split("""
Grid.h
""")

sources = Split("""
main.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #gk #cppdom #external/xdl'),
           LIBPATH = Split('#cppdom/cppdom #gk /usr/local/lib'),
           LIBS = Split('SDL gk cppdom opengl32 glu32') )
env.Append(CXXFLAGS = '-DXDL_USE_DLL')

if GetPlatform() == 'irix':
   env['SHCXXFLAGS'] = '${CXXFLAGS}'


env.Program('input', sources)

