import os
pj = os.path.join

Import('pkg baseEnv PREFIX GetPlatform')

headers = Split("""
Grid.h
""")

sources = Split("""
main.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #gk #cppdom #external/xdl'),
           LIBPATH = Split('#cppdom/cppdom #gk /usr/local/lib'),
           LIBS = Split('SDL gk cppdom') )

env.Append(CXXFLAGS = '-DXDL_USE_DLL')

if GetPlatform() == 'win32':
   env.Append(LIBS = Split('glu32 opengl32'))
else:
   env.Append(LIBS = Split('GLU GL pthread'))

if GetPlatform() == 'irix':
   env.Append(SHCXXFLAGS = '${CXXFLAGS}')


env.Program('input', sources)

