from os import path

Import('env PREFIX')

classes = Split("""
   BoundsCollisionDetector
   CollisionDesc
   RigidBody
""")

sources = []

headers = Split("""
   CollisionDetector.h
   SpatialIndex.h
   NullCollisionDetector.h
""")

sources.extend(map(lambda n: n + '.cpp', classes))
headers.extend(map(lambda n: n + '.h',   classes))

programs = []
programs.append(env.Program(target = 'midworld', source = sources))

env.Install(path.join(PREFIX, 'bin'), programs)
