Import('env')

classes = [
   'GameLogic',
   'Object',
   'Player',
]

headers = [
   'GameTimer',
   'UIDManager',
]

sources = [
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

# add in the files from classes
headers.extend( map(lambda fn: fn + '.h', classes) )
sources.extend( map(lambda fn: fn + '.cpp', classes) )

env.Library(target = 'game', source = sources)
