Import('env')


# XXXaegis - do we need headers?

headers = [
    'phui',
    'Button',
    'RootWidget',
    'WidgetContainer',
    'Widget',
    'Window',
]

sources = [
    'RootFactory',
    'RootWidget',
    'WidgetContainer',
    'Window',
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

env.Library(target = 'phui', source = sources)
