Import('env')


sources = [
    'Button.cpp',
    'Font.cpp',
    'FontRenderer.cpp',
    'Insets.cpp',
    'Label.cpp',
    'Rect.cpp',
    'RootFactory.cpp',
    'RootWidget.cpp',
    'TextField.cpp',
    'WidgetContainer.cpp',
    'Widget.cpp',
    'Window.cpp',
]

env.Library(target = 'phui', source = sources)
