Import('env')

sources = [
    'algebra3.cpp',
    'arcball.cpp',
    'glui_add_controls.cpp',
    'glui_bitmap_img_data.cpp',
    'glui_bitmaps.cpp',
    'glui_button.cpp',
    'glui_checkbox.cpp',
    'glui_column.cpp',
    'glui_control.cpp',
    'glui.cpp',
    'glui_edittext.cpp',
    'glui_listbox.cpp',
    'glui_mouse_iaction.cpp',
    'glui_node.cpp',
    'glui_panel.cpp',
    'glui_radio.cpp',
    'glui_rollout.cpp',
    'glui_rotation.cpp',
    'glui_separator.cpp',
    'glui_spinner.cpp',
    'glui_statictext.cpp',
    'glui_translation.cpp',
    'quaternion.cpp',
]

env.Library(target = 'glui', source = sources)
