import os
pj = os.path.join

Import('lib')

# Define the sources
classes = Split("""
   Jukebox
   SoundEffectManager
   SoundManager
""")

headers = []
sources = []

headers = map(lambda n: n + '.h',   classes)
sources = map(lambda n: n + '.cpp', classes)

# Clone the environment
lib.addSources(sources)
lib.addHeaders(headers, 'siren')
