import sys
Import('env')

headers = [
]

sources = [
   'window'
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

LIBS = ['phui', 'gltt', 'ttf']
if sys.platform == 'cygwin':
    LIBS.extend(['glut32', 'opengl32', 'glu32'])
else:
    LIBS.extend(['glut', 'GLU', 'GL'])

env2 = env.Copy( LIBPATH=['#phui'], LIBS=LIBS );
#env = Environment(CPPPATH='#', LIBPATH=['#phui', '/home/users/bscott/software/linux/lib'], LIBS=LIBS)
env2.Program(target = 'window', source = headers + sources)
