import sys

#Import('env')

headers = [
]

sources = [
   'window'
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

LIBS = ['phui']
if sys.platform == 'cygwin':
    LIBS += ['glut32', 'opengl32', 'glu32']
else:
    LIBS += ['glut', 'GLU', 'GL']

env = Environment(CPPPATH='#', LIBPATH='#phui', LIBS=LIBS)
env.Program(target = 'window', source = headers + sources)
