import sys
Import('env GLUT_LIBS FONT_LIBS')

headers = [
]

sources = [
   'window'
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

env2 = env.Copy(
         LIBS=['phui'] + GLUT_LIBS + FONT_LIBS
)
env2.Program(target = 'window', source = headers + sources)
