import os
pj = os.path.join

Import('baseEnv pkg')
Import('SetupAudiere SetupCal3D SetupCorona SetupOpenGL SetupSDL')
Import('SetupPython SetupBoostPython')

sources = ['main.cpp']

# Clone the environment
env = baseEnv.Copy()
SetupAudiere(env)
SetupCal3D(env)
SetupCorona(env)
SetupOpenGL(env)
SetupSDL(env)
env.Append(CPPPATH   = ['#'+pj('external','Loki'), '#src'])
env.Append(LIBPATH   = ['#'+pj('src', 'siren')],
           LIBS      = ['siren'],
           LINKFLAGS = Split('-Xlinker -export-dynamic'))
SetupBoostPython(env)
SetupPython(env, '2.2')
prog = pkg.createProgram('pyavatar', env)
prog.addSources(sources)
