import glob
import os
pj = os.path.join

Import('baseEnv builddir distdir')
Import('SetupPython')

# Build the barfight executable
env = baseEnv.Copy()
SetupPython(env, '2.2')
env.Append(LIBS = ['dl'],
           LINKFLAGS = Split('-Xlinker -export-dynamic'))
prog = env.Program('../barfight', 'Main.cpp')

# Copy the barfight executable to the dist directory
env.Install('../../dist', prog)

# The directories (in src) in which the python scripts lie
python_dirs = Split("""
   barfight
""")

# Copy the python scripts to the dist directory
for dir in python_dirs:
   pathname = pj(str(Dir('#src')), dir, '*.py')
   print 'pathname:',pathname
   python_scripts = glob.glob(pathname)

   for script in python_scripts:
      env.Install(pj('../../dist/lib', dir), script)
