import os
pj = os.path.join

Import('pkg baseEnv PREFIX GetPlatform')

headers = Split("""
SdlDriver.h
""")

sources = Split("""
SdlDriver.cpp
""")

env = baseEnv.Copy()
env.Append(CPPPATH = Split('# #gk #cppdom #external/xdl'),
           LIBPATH = Split('#cppdom/cppdom #gk /usr/local/lib'),
           LIBS = Split('cppdom SDL gk') )
env.Append(CXXFLAGS = ['-DXDL_BUILD_DLL'])

if GetPlatform() == 'irix':
   env['SHCXXFLAGS'] = '${CXXFLAGS}'

env.Replace(SHLIBPREFIX = '',
            SHLIBSUFFIX = '')

lib = pkg.createSharedLibrary('sdl.gkd', env)
lib.addSources(sources)
lib.addHeaders(headers, 'sdl.gkd')


