import os
import string

# build with 'scons'

Default('.')        # build everything by default

# Deterine the external libraries
execfile('opengl.py')
SDL_LIBS = ['SDL']
OSG_LIBS = ['osg', 'osgDB', 'osgUtil']
Export('OPENGL_LIBS SDL_LIBS OSG_LIBS')

CPPPATH=['#']

CXXFLAGS=['-Wall']
if ARGUMENTS.get('debug'):
    CXXFLAGS.extend(['-g'])

# setup the environment
env = Environment(CXXFLAGS=CXXFLAGS,CPPPATH=CPPPATH, ENV=os.environ)
Export('env')
SConscript('client/SConscript')
SConscript('game/SConscript')
SConscript('net/SConscript')
SConscript('server/SConscript')
SConscript('sound/SConscript')
SConscript('thread/SConscript')
