import os
import string

# build with 'scons'

Default('.')        # build everything by default

CPPPATH=['#']
# setup the environment
env = Environment(CPPPATH=CPPPATH, ENV=os.environ)
Export('env')
SConscript('net/SConscript')
SConscript('client/SConscript')
