import sys
Import('env')

classes = [
   'BrothaGame',
   'GameThread',
   'ListenServer',
   'WebServer',
]

headers = [
   'BrothaServer',
   'LoginMessageHandler',
   'MessageHandler',
]

sources = [
   'ConsoleServer',
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

# add in the files from classes
headers.extend( map(lambda fn: fn + '.h', classes) )
sources.extend( map(lambda fn: fn + '.cpp', classes) )


LIBS = ['net', 'game', 'nspr4', 'data', 'xmlpp']

env2 = env.Copy( LIBPATH=['#net', '#game', '#xml'], LIBS=LIBS );
env2.Program(target = 'server', source = sources)
