import sys
Import('env')

classes = [
   'AppState',
   'BrothaApp',
   'ModelManager',
]

headers = [
]

sources = [
   'main',
   'realmain',
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

# add in the files from classes
headers.extend( map(lambda fn: fn + '.h', classes) )
sources.extend( map(lambda fn: fn + '.cpp', classes) )


LIBS = ['gk', 'sound', 'net', 'game', 'nspr4', 'audiere', 'SDL', 'osg', 'osgDB']
if sys.platform == 'cygwin':
    LIBS.extend(['glut32', 'opengl32', 'glu32'])
else:
    LIBS.extend(['glut', 'GLU', 'GL'])

env2 = env.Copy( LIBPATH=['#net', '#game', '#sound'], LIBS=LIBS );
env2.Program(target = 'brotha', source = sources)
