import sys
Import('env')
Import('OPENGL_LIBS SDL_LIBS OSG_LIBS')

classes = [
#   'AppState',
   'BrothaApp',
   'Camera',
   'LoginState',
   'ModelManager',
   'Scene',
   'ServerConnection',
]

headers = [
    'State.h',
]

sources = [
    'main',
    'realmain',
]

# add proper extensions to filenames
headers = map(lambda fn: fn + '.h', headers)
sources = map(lambda fn: fn + '.cpp', sources)

# add in the files from classes
headers.extend( map(lambda fn: fn + '.h', classes) )
sources.extend( map(lambda fn: fn + '.cpp', classes) )

LIBS = ['sound', 'net', 'game', 'nspr4', 'audiere', 'phui', 'phuiSDL',
        'gltt', 'ttf'];
LIBS.extend(OPENGL_LIBS + SDL_LIBS + OSG_LIBS)

env2 = env.Copy( LIBPATH=['#net', '#game', '#sound'], LIBS=LIBS );
env2.Program(target = 'brotha', source = sources)
