Import('baseEnv pkg')
Import('SetupPython SetupBoostPython')

sources = Split("""
   main.cpp
""")

env = baseEnv.Copy()
env.Append(LIBPATH      = ['#phui'],
           LIBS         = Split('phui phuiGLUT util'),
           LINKFLAGS    = Split('-Xlinker -export-dynamic'))
SetupBoostPython(env)
SetupPython(env, '2.2')
prog = pkg.createProgram('py_example', env)
prog.addIncludes(['#'])
prog.addSources(sources)
