Import('baseEnv pkg')

sources = Split("""
   event.cpp
""")

env = baseEnv.Copy()
env.Append(LIBPATH = ['#phui'])
env.Append(LIBS = Split('phui phuiGLUT'))
prog = pkg.createProgram('event', env)
prog.addSources(sources)
